# Generated by Django 4.0.3 on 2023-01-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='tag',
        ),
        migrations.AddField(
            model_name='topic',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='forum.tag'),
        ),
    ]
